---
- name: "Create systemd service files"
  ansible.builtin.template:
    src: "push-kuma.service.j2"
    dest: "/etc/systemd/system/push-kuma.service"
    mode: "0660"

- name: "Create systemd timer files"
  ansible.builtin.template:
    src: "push-kuma.timer.j2"
    dest: "/etc/systemd/system/push-kuma.timer"
    mode: "0660"

- name: "Make sure that the timer units are enabled and started"
  become: true
  ansible.builtin.systemd:
    name: "push-kuma.timer"
    state: started
    enabled: true
    daemon_reload: true
