---
- name: "Install curl (Debian derivatives)"
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: "Install curl (RHEL derivatives)"
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: curl
    state: present

- name: "Configure and deploy systemd service"
  loop: "{{ services }}"
  loop_control:
    loop_var: "job"
  ansible.builtin.include_tasks: "deploy-service.yml"
