---
- name: "Install curl (Debian derivatives)"
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: true

- name: "Install curl (RHEL derivatives)"
  when: ansible_os_family == "RedHat"
  ansible.builtin.dnf:
    name: curl
    state: present

- name: "Create systemd service files"
  ansible.builtin.template:
    src: "curl-scheduled.service.j2"
    dest: "/etc/systemd/system/curl-scheduled.service"
    mode: "0660"

- name: "Create systemd timer files"
  ansible.builtin.template:
    src: "curl-scheduled.timer.j2"
    dest: "/etc/systemd/system/curl-scheduled.timer"
    mode: "0660"

- name: "Make sure that the timer units are enabled and started"
  become: true
  ansible.builtin.systemd:
    name: "curl-scheduled.timer"
    state: started
    enabled: true
    daemon_reload: true
