---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Create test directory"
      ansible.builtin.file:
        path: "/test"
        state: directory
        mode: "0664"

    - name: "Create a test file"
      ansible.builtin.lineinfile:
        path: "/test/index.html"
        create: true
        mode: "0664"
        line: "OK"

    - name: "Simulate a remote HTTP server on localhost - localhost-test-zero"
      changed_when: false
      async: 1
      poll: 0
      args:
        chdir: "/test"
      ansible.builtin.shell:
        cmd: nohup python3 -m http.server 8080 </dev/null >/dev/null 2>&1 &
        executable: /bin/bash

    - name: "Simulate a remote HTTP server on localhost - localhost-test-one"
      changed_when: false
      async: 1
      poll: 0
      args:
        chdir: "/test"
      ansible.builtin.shell:
        cmd: nohup python3 -m http.server 8081 </dev/null >/dev/null 2>&1 &
        executable: /bin/bash

  roles:
    - role: genlab.curl_scheduled
      services:
        - label: "localhost-test-zero"
          url: "http://127.0.0.1:8080"
          schedule: minutely
        - label: "localhost-test-one"
          url: "http://127.0.0.1:8081"
          schedule: hourly
