---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check that the service file exists"
      register: service_file
      failed_when: service_file.stat.exists == false
      ansible.builtin.stat:
        path: "/etc/systemd/system/push-kuma.service"

    - name: "Check that the timer file exists"
      register: timer_file
      failed_when: timer_file.stat.exists == false
      ansible.builtin.stat:
        path: "/etc/systemd/system/push-kuma.timer"

    # - name: "Assert service file exists"
    #   ansible.builtin.assert:
    #     that:
    #       - service_file.stat.exists == true
    #     success_msg: "Service file exists"
    #     fail_msg: "Service file does not exist"

    # - name: "Assert timer file exists"
    #   ansible.builtin.assert:
    #     that:
    #       - timer_file.stat.exists == true
    #     success_msg: "Timer file exists"
    #     fail_msg: "Timer file does not exist"
