---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: "Check the timer status"
      register: timer
      ansible.builtin.systemd:
        name: "curl-scheduled.timer"

    - name: "Assert that the timer is running"
      ansible.builtin.assert:
        that:
          - timer.status.ActiveState == "active"
        success_msg: "Timer is running"
        fail_msg: "Unexpected timer state: '{{ timer.status.ActiveState }}'"

    - name: "Check the service status"
      register: service
      ansible.builtin.systemd:
        name: "curl-scheduled.service"

    - name: "Assert that the service exited with a 0/SUCCESS status"
      ansible.builtin.assert:
        that:
          - 'service.status.ExecMainStatus == "0"'
        success_msg: "Service has exited with a 0/SUCCESS status"
        fail_msg: "Unexpected service status code: '{{ service.status.ExecMainStatus }}'"
